```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
#Fuerza de trabajo
library(dplyr)
setwd('C:/Users/Usuario/Desktop/Tae')
base <- read.csv("Fuerza de trabajo.csv",header = TRUE,sep=";",dec=",")
```

```{r}
#Selección variables y renombrado
df1 <- base %>% select(ï..DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,P6240,P6250,P6435,P8624,P8630,P415,P8644)
colnames(df1) <- c('ï..DIRECTORIO','SECUENCIA_ENCUESTA','SECUENCIA_P','actividad_semana_pasada', 'actividad_paga_pasada', 'trabajo', 'ganancia', 'subsidio_familiar','horas','sostenimiento_hijos')

#Conversión a categoría
cols <- c("actividad_semana_pasada", "actividad_paga_pasada","trabajo","subsidio_familiar","sostenimiento_hijos")
df1[,cols] <- lapply(df1[,cols], factor)

#Manejo de nulos
df1$actividad_semana_pasada[is.na(df1$actividad_semana_pasada)] <- "6"
df1$actividad_paga_pasada[is.na(df1$actividad_paga_pasada)] <- "2"
df1$trabajo[is.na(df1$trabajo)] <- "0"
df1$ganancia[is.na(df1$ganancia)] <- "0"
df1$horas[is.na(df1$horas)] <- "0"
df1$subsidio_familiar[is.na(df1$subsidio_familiar)] <- "9"
df1$sostenimiento_hijos[is.na(df1$sostenimiento_hijos)] <- "9"

#Renombrado respuestas
df1 %>% 
  mutate(cg = case_when(actividad_semana_pasada == 1 ~ "Trabajando",
                        actividad_semana_pasada == 2  ~ "Buscando trabajo",
                        actividad_semana_pasada == 3 ~ "Estudiando",
                        actividad_semana_pasada == 4  ~ "Oficios del hogar",
                        actividad_semana_pasada == 5 ~ "Incapacitado permanentemente",
                        actividad_semana_pasada == 6  ~ "Otra actividad"))
df1 %>% 
  mutate(cg = case_when(actividad_paga_pasada == 1 ~ "Si",
                        actividad_paga_pasada == 2  ~ "No"))
df1 %>% 
  mutate(cg = case_when(trabajo == 0 ~ "No aplica",
                        trabajo == 1 ~ "Empleado empresa particular",
                        trabajo == 2  ~ "Empleado gobierno",
                        trabajo == 3 ~ "Empleado doméstico",
                        trabajo == 4  ~ "Profesional independiente",
                        trabajo == 5  ~ "Trabajador independiente",
                        trabajo == 6 ~ "Patron o empleado",
                        trabajo == 7  ~ "Trabajador de finca",
                        trabajo == 8  ~ "Trabajador sin remuneración",
                        trabajo == 9  ~ "Ayudante sin remuneración",
                        trabajo == 10  ~ "Jornalero de peon"))
df1 %>% 
  mutate(cg = case_when(subsidio_familiar == 1 ~ "Si",
                        subsidio_familiar == 2  ~ "No",
                        subsidio_familiar == 9  ~ "No sabe, no informa"))
df1 %>% 
  mutate(cg = case_when(sostenimiento_hijos == 1 ~ "Si",
                        sostenimiento_hijos == 2  ~ "No",
                        sostenimiento_hijos == 9  ~ "No sabe, no informa"))

head(df1)
```


```{r}
#Tenencia y financiación de la vivienda que ocupa el hogar
library(dplyr)
setwd('C:/Users/Usuario/Desktop/Tae')
base2 <- read.csv("Tenencia y financiación de la vivienda que ocupa el hogar.csv",header = TRUE,sep=";",dec=",")
```

```{r}
#Selección variables y renombrado
df2 <- base2 %>% select(ï..DIRECTORIO,SECUENCIA_ENCUESTA,SECUENCIA_P,P5095,P5100,P5110,P5130,P5140,P5160)
colnames(df2) <- c('ï..DIRECTORIO','SECUENCIA_ENCUESTA','SECUENCIA_P','vivienda_es', 'amortizuacion', 'precio_venta', 'precio_arriendo','pago_arriendo', 'subsidio_vivienda')
#Conversión a categoría
cols <- c("vivienda_es", "subsidio_vivienda")
df2[,cols] <- lapply(df2[,cols], factor)
#Manejo de nulos
df2$amortizuacion[is.na(df2$amortizuacion)] <- "0"
df2$precio_venta[is.na(df2$precio_venta)] <- "0"
df2$precio_arriendo[is.na(df2$precio_arriendo)] <- "0"
df2$pago_arriendo[is.na(df2$pago_arriendo)] <- "0"
df2$subsidio_vivienda[is.na(df2$subsidio_vivienda)] <- "2"
head(df2)
```



```{r}
library("writexl")
write_xlsx(df1,"C:\\Users\\Usuario\\Desktop\\Fuerza de trabajo Procesada.xlsx")
write_xlsx(df2,"C:\\Users\\Usuario\\Desktop\\Tenencia de vivienda Procesada.xlsx")
```



